import { Inter } from "next/font/google";
import "./globals.css";
// 1. import `NextUIProvider` component
import {NextUIProvider} from "@nextui-org/react";
import Navbar from "@/compoenents/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextUIProvider>
      <div className="max-w-3xl mx-auto p-4">           
        <Navbar/>
        </div>
        {children}
       
        </NextUIProvider>
        </body>
    </html>
  );
}
